backend/hhrr_app/views/db_employee.py
import os
from datetime import datetime, date
from email import message
from flask_wtf import CSRFProtect
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Blueprint, flash, redirect, render_template, request, session, url_for

from hhrr_app import db
from hhrr_app import forms
from hhrr_app.models.tbl_rh import RH
from hhrr_app.models.tbl_aap import AAP
from hhrr_app.models.tbl_afp import AFP
from hhrr_app.models.tbl_ccf import CCF
from hhrr_app.models.tbl_arl import ARL
from hhrr_app.models.tbl_eps import EPS
from hhrr_app.models.tbl_city import City
from hhrr_app.models.tbl_race import Race
from hhrr_app.models.tbl_roles import Role
from hhrr_app.models.tbl_type_id import TypeId
from hhrr_app.models.tbl_employee import Employee
from hhrr_app.models.tbl_diseases import Diseases
from hhrr_app.models.tbl_age_range import AgeRange
from hhrr_app.models.tbl_house_type import HouseType
from hhrr_app.models.tbl_department import Department
from hhrr_app.models.tbl_work_shift import WorkShift
from hhrr_app.models.tbl_ss_employee import SSEmployee
from hhrr_app.models.tbl_relationship import Relationship
from hhrr_app.models.tbl_subhouse_type import SubHouseType
from hhrr_app.models.tbl_marital_status import MaritalStatus
from hhrr_app.models.tbl_family_nucleus import FamilyNucleus
from hhrr_app.models.tbl_schooling_level import SchoolingLevel
from hhrr_app.models.tbl_demographic_data import DemographicData
from hhrr_app.models.tbl_health_condition import HealthCondition
from hhrr_app.models.tbl_type_contributor import TypeContributor
from hhrr_app.models.tbl_type_affiliation import TypeAffiliation
from hhrr_app.models.tbl_type_relationship import TypeRelationship
from hhrr_app.models.tbl_auto_perceived_gender import AutoPerceivedGender
from hhrr_app.models.tbl_sociodemographic_data import SociodemographicData
from hhrr_app.models.tbl_employment_relationship import EmploymentRelationship
from hhrr_app.models.tbl_emergency_contact_details import EmergencyContactDetails


blueprint_db_employee = Blueprint("db_employee", __name__, url_prefix="")

# CREATE READ UPDATE DELETE BASIC DATA EMPLOYEE
@blueprint_db_employee.route("/registerEmployee", methods=["GET", "POST"])
def registerEmployee():
    form = forms.RegisterEmployee(request.form)
    if request.method == "GET":
        return render_template("login/signup.html", form=form)
    else:

        ccn_type_id = request.form["ccn_type_id"]
        number_id_employee = request.form["number_id_employee"]
        first_name_employee = request.form["first_name_employee"].upper()
        middle_name_employee = request.form["middle_name_employee"].upper()
        first_last_name_employee = request.form["first_last_name_employee"].upper()
        second_last_name_employee = request.form["second_last_name_employee"].upper()
        full_name_employee = (
            first_name_employee
            + " "
            + middle_name_employee
            + " "
            + first_last_name_employee
            + " "
            + second_last_name_employee
        )
        date_birth_employee = request.form["date_birth_employee"]
        date_birth = datetime.strptime(
            date_birth_employee.replace("-", "/"), "%Y/%m/%d"
        )
        year = datetime.now()
        if int(date_birth.month) > int(year.month):
            age = int(year.year) - int(date_birth.year) - 1
        else:
            if int(date_birth.day) <= int(year.day):
                age = int(year.year) - int(date_birth.year)
            else:
                age = int(year.year) - int(date_birth.year) - 1
        list_age_range = ["5", "6", "7", "8", "9"]

        if list(str(age))[1] in list_age_range:
            age_range = f"{list(str(age))[0]}5-{list(str(age))[0]}9"
        else:
            age_range = f"{list(str(age))[0]}0-{list(str(age))[0]}4"

        query_age_range = AgeRange.query.filter_by(age_range=age_range).first()
        age_range = query_age_range.ccn_age_range
        auto_perceived_gender = request.form["auto_perceived_gender"]
        rh = request.form["rh"]
        employee_personal_email = request.form["employee_personal_email"].upper()
        employee_personal_cellphone = request.form["employee_personal_cellphone"]
        informed_consent_law_1581 = "yes"

        if request.files["img_employee"]:
            employee_photo = request.files["img_employee"]
            filename = secure_filename(employee_photo.filename)
            image = filename
            employee_photo.save(
                os.path.join("hhrr_app/static/images/employee_photos", filename)
            )

        else:
            image = "not_registered.jpg"

        employee_password = generate_password_hash(request.form["employee_password"])

        new_employee = Employee(
            ccn_type_id,
            number_id_employee,
            first_name_employee,
            middle_name_employee,
            first_last_name_employee,
            second_last_name_employee,
            full_name_employee,
            date_birth_employee,
            age,
            age_range,
            auto_perceived_gender,
            rh,
            employee_personal_email,
            employee_personal_cellphone,
            informed_consent_law_1581,
            image,
            employee_password,
        )

        db.session.add(new_employee)
        db.session.commit()

        return redirect(url_for("db_employee.list_employee"))


@blueprint_db_employee.route("/list_employee", methods=["GET", "POST"])
@blueprint_db_employee.route("/list_employee/<message>", methods=["GET", "POST"])
def list_employee(message=None):
    title = "List Employees"
    form = forms.RegisterEmployee()
    if "user_name" in session:
        user_name = session["user_name"]
        query_logged_user = Employee.query.filter(
            Employee.employee_personal_email == user_name
        ).first()
        user_html = query_logged_user.full_name_employee
        if request.method == "GET":
            query_list_employee = Employee.query.all()
            return render_template(
                "database_employees/basic_data_employee.html",
                query_logged_user=query_logged_user,
                query_list_employee=query_list_employee,
                title=title,
                user=user_name,
                form=form,
                user_html=user_html,
                message=message,
            )
        else:
            return render_template(
                "database_employees/basic_data_employee.html",
                query_logged_user=query_logged_user,
                query_list_employee=query_list_employee,
                title=title,
                user=user_name,
                form=form,
                user_html=user_html,
                message=message,
            )
    else:
        mensajeErrorSesion = "There is no active session please enter the platform"
        flash(mensajeErrorSesion)
        return redirect(url_for("landingPage.index"))


@blueprint_db_employee.route(
    "/update_employee/<int:ccn_employee>", methods=["GET", "POST"]
)
def update_employee(ccn_employee):
    if request.method == "GET":

        query_employee = Employee.query.filter_by(ccn_employee=ccn_employee).first()
        query_auto_perceived_gender = AutoPerceivedGender.query.filter_by(
            ccn_auto_perceived_gender=query_employee.auto_perceived_gender
        ).first()
        query_age_range = AgeRange.query.filter_by(
            ccn_age_range=query_employee.age_range
        ).first()
        query_rh = RH.query.filter_by(ccn_rh=query_employee.rh).first()
        query_type_id = TypeId.query.filter_by(
            ccn_type_id=query_employee.ccn_type_id
        ).first()

        form = forms.RegisterEmployee(
            ccn_type_id=query_type_id,
            number_id_employee=query_employee.number_id_employee,
            first_name_employee=query_employee.first_name_employee,
            middle_name_employee=query_employee.middle_name_employee,
            first_last_name_employee=query_employee.first_last_name_employee,
            second_last_name_employee=query_employee.second_last_name_employee,
            full_name_employee=query_employee.full_name_employee,
            date_birth_employee=query_employee.date_birth_employee,
            age=query_employee.age,
            age_range=query_age_range,
            auto_perceived_gender=query_auto_perceived_gender,
            rh=query_rh,
            employee_personal_email=query_employee.employee_personal_email,
            employee_personal_cellphone=query_employee.employee_personal_cellphone,
            image=query_employee.image,
            employee_password=query_employee.employee_password,
        )
        return render_template(
            "database_employees/update_data_employee.html",
            form=form,
            query_employee=query_employee,
            ccn_employee=ccn_employee,
        )
    elif request.method == "POST":

        query_employee = Employee.query.filter_by(ccn_employee=ccn_employee).first()

        query_employee.ccn_type_id = request.form["ccn_type_id"]
        query_employee.number_id_employee = request.form["number_id_employee"]
        query_employee.first_name_employee = request.form["first_name_employee"].upper()
        query_employee.middle_name_employee = request.form[
            "middle_name_employee"
        ].upper()
        query_employee.first_last_name_employee = request.form[
            "first_last_name_employee"
        ].upper()
        query_employee.second_last_name_employee = request.form[
            "second_last_name_employee"
        ].upper()
        query_employee.full_name_employee = (
            request.form["first_name_employee"].upper()
            + " "
            + request.form["middle_name_employee"].upper()
            + " "
            + request.form["first_last_name_employee"].upper()

backend/hhrr_app/templates/database_employees/basic_data_employee.html
{% extends "home/base_home.html" %} {% block title %}{{ titulo }}{% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}

<div class="container-fluid text-end justify-content-center align-items-lg-center">
  <h4><strong>{{query_logged_user.employee_personal_email}}</strong></h4>
  <h6><strong>{{query_logged_user.full_name_employee}}</strong></h6>
</div>

<!-- Button trigger modal -->
<div class="container-fluid py-2">
  <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    NEW EMPLOYEE
  </button>
</div>

<div class="container-fluid">
  <table class="table caption-top responsive table-hover" id="table_employee" cellspacing="0" style="width: 100%">
    <thead>
      <tr>
        <th class="text-center">CCN</th>
        <th class="text-center">ID</th>
        <th class="text-end">NUMBER ID</th>
        <th class="text-start">FULL NAME</th>
        <th class="text-center">BIRTH DATE</th>
        <th class="text-center">AGE</th>
        <th class="text-center">AGE RANGE</th>
        <th class="text-center">GENDER</th>
        <th class="text-center">RH</th>
        <th class="text-start">EMAIL ADDRESS</th>
        <th class="text-end">PHONE NUMBER</th>
        <th class="text-center">LAW 1581</th>
        <th class="text-center">ACTIONS</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for employee in query_list_employee %}
      <tr>
        <td class="text-center">{{ employee.ccn_employee }}</td>
        <td class="text-center">{{ employee.TypeId.type_id }}</td>
        <td class="text-end">{{ employee.number_id_employee }}</td>
        <td class="text-start">{{ employee.full_name_employee }}</td>
        <td class="text-center">{{ employee.date_birth_employee }}</td>
        <td class="text-center">{{ employee.age }}</td>
        <td class="text-center">{{ employee.AgeRange.age_range }}</td>
        <td class="text-center">
          {{ employee.AutoPerceivedGender.auto_perceived_gender }}
        </td>
        <td class="text-center">{{ employee.RH.rh }}</td>
        <td class="text-start">{{ employee.employee_personal_email }}</td>
        <td class="text-end">{{ employee.employee_personal_cellphone }}</td>
        <td class="text-center">{{ employee.informed_consent_law_1581 }}</td>
        <td>
          <a class="btn btn-secondary btn-sm m-1" href="/update_employee/{{ employee.ccn_employee }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
              <path fill-rule="evenodd"
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
            </svg>
          </a>
          <a class="btn btn-secondary btn-sm m-1" href="/cv_employee/{{employee.ccn_employee}}">
            <img src="../../static/images/curriculum-vitae-curriculum-svgrepo-com.svg" alt="" height="20">
          </a>
          <!-- <a class="btn btn-danger btn-sm" href="#" id="Eliminacion">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-trash" viewBox="0 0 16 16">
                        <path
                            d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                        <path fill-rule="evenodd"
                            d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                    </svg>
                </a> -->
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.colVis.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.4.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/responsive.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.colVis.min.js"></script>

<script>

  $(document).ready(function () {
    var table = $("#table_employee").DataTable({
      searchable: true,
      fixedHeight: true,
      responsive: true,
      paging: true,
      order: [[0, "dsc"]],
      select: true,
      autoFill: true,
      dom: '<Cfl><"top"p>rt<"bottom"p><BRSPQ><"clear">',
      buttons: [
        {
          extend: "colvis",
          extend: 'columnsToggle',
          extend: "excel",
          title: "Archivo",
          filename: "Export_File_xlxs",
          text: '<img src="../../static/images/excel.png" width="30" height="30">',
        },
      ],
    });

    new $.fn.dataTable.Responsive(table, {
      details: false,
    });

    new $.fn.dataTable.ColReorder(table, {
      realtime: true
    });
    table.buttons().container().appendTo($("", table.table().container()));
  });
</script>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">
          CREATE A NEW EMPLOYEE
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <form class="row g-1" action="{{ url_for('db_employee.registerEmployee') }}" method="POST"
              enctype="multipart/form-data">
              {{ form.hidden_tag() }}

              <div class="col-md-6 col-lg-6">
                {{ form.ccn_type_id.label(class="mt-1") }} {{
                form.ccn_type_id(class="form-control") }} {% for error in
                form.ccn_type_id.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-6 col-lg-6">
                {{ form.number_id_employee.label(class="mt-1") }} {{
                form.number_id_employee(class="form-control") }} {% for error in
                form.number_id_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.first_name_employee.label(class="mt-1") }} {{
                form.first_name_employee(class="form-control") }} {% for error
                in form.first_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.middle_name_employee.label(class="mt-1") }} {{
                form.middle_name_employee(class="form-control") }} {% for error
                in form.middle_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.first_last_name_employee.label(class="mt-1") }} {{
                form.first_last_name_employee(class="form-control") }} {% for
                error in form.first_last_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.second_last_name_employee.label(class="mt-1") }} {{
                form.second_last_name_employee(class="form-control") }} {% for
                error in form.second_last_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-3">
                {{ form.date_birth_employee.label(class="mt-1") }} {{
                form.date_birth_employee(class="form-control") }} {% for error
                in form.date_birth_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-3">
                {{ form.rh.label(class="mt-1") }} {{
                form.rh(class="form-control") }} {% for error in form.rh.errors
                %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.auto_perceived_gender.label(class="mt-1") }} {{
                form.auto_perceived_gender(class="form-control") }} {% for error
                in form.auto_perceived_gender.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.employee_personal_email.label(class="mt-1") }} {{
                form.employee_personal_email(class="form-control") }} {% for
                error in form.employee_personal_email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.employee_personal_cellphone.label(class="mt-1") }} {{
                form.employee_personal_cellphone(class="form-control") }} {% for
                error in form.employee_personal_cellphone.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12">
                {{ form.img_employee.label(class="mt-1") }} {{
                form.img_employee(class="form-control") }} {% for error in
                form.img_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-12">
                {{ form.employee_password.label(class="mt-1") }} {{
                form.employee_password(class="form-control mb-3") }} {% for
                error in form.employee_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              <br />
              <div class="col-md-12 col-lg-12">
                {{ form.submit(class="btn btn-success") }} {% for error in
                form.submit.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

backend/hhrr_app/templates/database_employees/update_data_employee.html
{% extends "home/base_home.html" %}{% block content %}

<div class="mx-auto mt-3 container-fluid bg-white">
  <div class="row">
    <div class="col-lg-3 border-right">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <img
          class="mt-5"
          width="250px"
          src="../../static/images/employee_photos/{{ query_employee.image }}"
        /><span class="font-weight-bold"
          >{{ query_employee.full_name_employee }}</span
        ><span class="text-black-50"
          >{{ query_employee.employee_personal_email }}</span
        ><span> </span>
      </div>
    </div>
    <div class="col-md-9">
      <div class="my-3">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4>UPDATE BASIC INFORMATION EMPLOYEE</h4>
        </div>

        <div class="container-fluid">
          <div class="my-3">
            <form
              class="row g-1"
              action="{{ url_for('db_employee.update_employee',ccn_employee=ccn_employee) }}"
              method="POST"
              enctype="multipart/form-data"
            >
              {{ form.hidden_tag() }}

              <div class="col-md-6 col-lg-6">
                {{ form.ccn_type_id.label(class="mt-1") }} {{
                form.ccn_type_id(class="form-control") }} {% for error in
                form.ccn_type_id.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-6 col-lg-6">
                {{ form.number_id_employee.label(class="mt-1") }} {{
                form.number_id_employee(class="form-control") }} {% for error in
                form.number_id_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.first_name_employee.label(class="mt-1") }} {{
                form.first_name_employee(class="form-control") }} {% for error
                in form.first_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.middle_name_employee.label(class="mt-1") }} {{
                form.middle_name_employee(class="form-control") }} {% for error
                in form.middle_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.first_last_name_employee.label(class="mt-1") }} {{
                form.first_last_name_employee(class="form-control") }} {% for
                error in form.first_last_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.second_last_name_employee.label(class="mt-1") }} {{
                form.second_last_name_employee(class="form-control") }} {% for
                error in form.second_last_name_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-2">
                {{ form.date_birth_employee.label(class="mt-1") }} {{
                form.date_birth_employee(class="form-control") }} {% for error
                in form.date_birth_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              
              <div class="col-md-12 col-lg-2">
                {{ form.age.label(class="mt-1") }} {{
                form.age(class="form-control",disabled=True) }} {% for error in
                form.age.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-2">
                {{ form.age_range.label(class="mt-1") }} {{
                form.age_range(class="form-control",disabled=True) }} {% for error in
                form.age_range.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-3">
                {{ form.auto_perceived_gender.label(class="mt-1") }} {{
                form.auto_perceived_gender(class="form-control") }} {% for error
                in form.auto_perceived_gender.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-3">
                {{ form.rh.label(class="mt-1") }} {{
                form.rh(class="form-control") }} {% for error in form.rh.errors
                %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.employee_personal_email.label(class="mt-1") }} {{
                form.employee_personal_email(class="form-control") }} {% for
                error in form.employee_personal_email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-6">
                {{ form.employee_personal_cellphone.label(class="mt-1") }} {{
                form.employee_personal_cellphone(class="form-control") }} {% for
                error in form.employee_personal_cellphone.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12">
                {{ form.img_employee.label(class="mt-1") }} {{
                form.img_employee(class="form-control") }} {% for error in
                form.img_employee.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-12 col-lg-12">
                {{ form.employee_password.label(class="mt-1") }} {{
                form.employee_password(class="form-control") }} {% for error in
                form.employee_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="my-4 col-md-12 col-lg-6">
                <a class="btn btn-secondary" href="/list_employee">Return</a>
                {{ form.submit(class="btn btn-success",value="Update") }} {% for
                error in form.submit.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}