backend/hhrr_app/views/defined_codes.py
from flask import flash
from email import message
from flask import request
from flask import session
from flask import url_for
from flask import redirect
from flask import Blueprint
from flask_wtf import CSRFProtect
from flask import render_template

from hhrr_app import db
from hhrr_app import forms

from hhrr_app.models.tbl_rh import RH
from hhrr_app.models.tbl_eps import EPS
from hhrr_app.models.tbl_afp import AFP
from hhrr_app.models.tbl_arl import ARL
from hhrr_app.models.tbl_ccf import CCF
from hhrr_app.models.tbl_aap import AAP
from hhrr_app.models.tbl_city import City
from hhrr_app.models.tbl_race import Race
from hhrr_app.models.tbl_roles import Role
from hhrr_app.models.tbl_type_id import TypeId
from hhrr_app.models.tbl_country import Country
from hhrr_app.models.tbl_employee import Employee
from hhrr_app.models.tbl_diseases import Diseases
from hhrr_app.models.tbl_age_range import AgeRange
from hhrr_app.models.tbl_work_shift import WorkShift
from hhrr_app.models.tbl_house_type import HouseType
from hhrr_app.models.tbl_department import Department
from hhrr_app.models.tbl_subhouse_type import SubHouseType
from hhrr_app.models.tbl_marital_status import MaritalStatus
from hhrr_app.models.tbl_schooling_level import SchoolingLevel
from hhrr_app.models.tbl_type_affiliation import TypeAffiliation
from hhrr_app.models.tbl_type_contributor import TypeContributor
from hhrr_app.models.tbl_type_relationship import TypeRelationship
from hhrr_app.models.tbl_auto_perceived_gender import AutoPerceivedGender
from hhrr_app.models.tbl_employment_relationship import EmploymentRelationship


blueprint_defined_codes = Blueprint("defined_codes", __name__, url_prefix="")


# CREATE READ UPDATE DELETE COUNTRY
@blueprint_defined_codes.route("/create_country", methods=["GET", "POST"])
def create_country():
    title = "Countries"
    if "user_name" in session:
        user_name = session["user_name"]
        form = forms.CreateCountry(request.form)
        # q = Employee.query.filter(Employee.employee_email == user_name).first()
        if request.method == "GET":
            return render_template(
                "fixed_assets/create_fixed_asset.html",
                title=title,
                user=user_name,
                form=form,
            )
        else:
            id_country = request.form["id_country"].upper()
            description_country = request.form["description_country"].upper()

            new_country = Country(
                id_country,
                description_country,
            )

            db.session.add(new_country)
            db.session.commit()

            type_mmesage = "create"
            flash(f"{description_country} has been created correctly")

            return redirect(
                url_for(
                    "defined_codes.defined_code_country",
                    flash=flash,
                    message=type_mmesage,
                )
            )
    else:
        mensajeErrorSesion = "There is no active session please enter the platform"
        flash(mensajeErrorSesion)

        return redirect(url_for("index.index"))


@blueprint_defined_codes.route("/defined_code_country", methods=["GET", "POST"])
@blueprint_defined_codes.route(
    "/defined_code_country/<message>", methods=["GET", "POST"]
)
def defined_code_country(message=None):
    message = message
    title = "Defined Code Country"
    form = forms.CreateCountry(request.form)
    if "user_name" in session:
        user_name = session["user_name"]
        query_logged_user = Employee.query.filter(
            Employee.employee_personal_email == user_name
        ).first()
        if request.method == "GET":
            q_defined_code_country = Country.query.all()
            return render_template(
                "defined_codes/defined_codes_country.html",
                list_defined_code_country=q_defined_code_country,
                title=title,
                user=user_name,
                form=form,
                query_logged_user=query_logged_user,
                message=message,
            )
        else:
            return render_template(
                "defined_codes/defined_codes_country.html",
                user=user_name,
                form=form,
                query_logged_user=query_logged_user,
                message=message,
            )
    else:
        mensajeErrorSesion = "There is no active session please enter the platform"
        flash(mensajeErrorSesion)
        return redirect(url_for("landingPage.index"))


@blueprint_defined_codes.route(
    "/update_country/<int:ccn_country>", methods=["GET", "POST"]
)
def update_country(ccn_country):
    if request.method == "GET":
        q = Country.query.filter_by(ccn_country=ccn_country).first()
        form = forms.CreateCountry(
            id_country=q.id_country, description_country=q.description_country
        )
        return render_template(
            "defined_codes/update_country.html", form=form, q=q, ccn_country=ccn_country
        )
    elif request.method == "POST":
        q = db.session.query(Country).filter_by(ccn_country=ccn_country).first()
        q.description_country = request.form["description_country"].upper()
        q.id_country = request.form["id_country"].upper()
        form = forms.CreateCountry(request.form)
        db.session.commit()

        type_message = "update"
        flash(f"{q.description_country} has been updated correctly")
        return redirect(
            url_for(
                "defined_codes.defined_code_country", flash=flash, message=type_message
            )
        )


@blueprint_defined_codes.route(
    "/delete_country/<int:ccn_country>", methods=["GET", "POST"]
)
def delete_country(ccn_country):
    form = forms.CreateCountry(request.form)
    if "user_name" in session:
        Country.delete_country(ccn_country)
        type_message = "delete"
        flash(f"The Country has been deleted correctly")

        return redirect(
            url_for(
                "defined_codes.defined_code_country", flash=flash, message=type_message
            )
        )


# CREATE READ UPDATE DELETE DEPARTMENT
@blueprint_defined_codes.route("/create_department", methods=["GET", "POST"])
def create_department():
    title = "Cities"
    if "user_name" in session:
        user_name = session["user_name"]
        form = forms.CreateDepartment(request.form)
        # q = Employee.query.filter(Employee.employee_email == user_name).first()
        if request.method == "GET":
            return render_template(
                "fixed_assets/create_fixed_asset.html",
                title=title,
                user=user_name,
                form=form,
            )
        else:
            id_department = request.form["id_department"].upper()
            descripcion_department = request.form["descripcion_department"].upper()
            ccn_country = request.form["ccn_country"].upper()

            new_department = Department(
                id_department,
                descripcion_department,
                ccn_country,
            )

            db.session.add(new_department)
            db.session.commit()

            type_message = "create"
            flash(f"{descripcion_department} has been created correctly")

            return redirect(
                url_for(
                    "defined_codes.defined_code_department",
                    flash=flash,
                    message=type_message,
                )
            )
    else:
        mensajeErrorSesion = "There is no active session please enter the platform"
        flash(mensajeErrorSesion)

        return redirect(url_for("index.index"))


@blueprint_defined_codes.route("/defined_code_department", methods=["GET", "POST"])
@blueprint_defined_codes.route(
    "/defined_code_department/<message>", methods=["GET", "POST"]
)
def defined_code_department(message=None):
    message = message
    title = "Defined Code Department"
    form = forms.CreateDepartment(request.form)
    if "user_name" in session:
        user_name = session["user_name"]
        query_logged_user = Employee.query.filter(
            Employee.employee_personal_email == user_name
        ).first()

        if request.method == "GET":
            query_list_departments = Department.query.all()

            return render_template(
                "defined_codes/defined_codes_department.html",
                query_logged_user=query_logged_user,
                query_list_departments=query_list_departments,
                title=title,
                user=user_name,
                form=form,
                message=message,
            )
        else:
            query_list_departments = Department.query.all()
            return render_template(
                "defined_codes/defined_codes_department.html",
                query_logged_user=query_logged_user,
                query_list_departments=query_list_departments,
                user=user_name,
                form=form,
            )
    else:
        mensajeErrorSesion = "There is no active session please enter the platform"
        flash(mensajeErrorSesion)
        return redirect(url_for("landingPage.index"))


@blueprint_defined_codes.route(
    "/update_department/<int:id_department>", methods=["GET", "POST"]
)
def update_department(id_department):
    if request.method == "GET":
        q = Department.query.filter_by(id_department=id_department).first()
        q_country = Country.query.filter_by(ccn_country=q.ccn_country).first()
        form = forms.CreateDepartment(
            id_department=q.id_department,
            descripcion_department=q.descripcion_department,
            ccn_country=q_country,
        )
        return render_template(
            "defined_codes/update_department.html",
            form=form,
            q=q,
            id_department=id_department,
        )
    elif request.method == "POST":

backend/hhrr_app/templates/defined_codes/defined_codes_age_range.html
{% extends "home/base_home.html" %} {% block title %}{{ titulo }}{% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}

<div class="container-fluid text-end justify-content-center align-items-lg-center">
    <h4><strong>{{query_logged_user.employee_personal_email}}</strong></h4>
    <h6><strong>{{query_logged_user.full_name_employee}}</strong></h6>
</div>

<div class="container-fluid py-3">
    <div class="row">
        <div class="col-lg-10">
            <!-- Button trigger modal -->
            <div>
                <button type="button" class="btn btn-success btn-sm py-2" data-bs-toggle="modal"
                    data-bs-target="#staticBackdrop">
                    NUEVA AGE RANGE
                </button>
                <div class="table-responsive col-md-12">
                    <table class="table table-hover table-responsive" id="table_race" cellspacing="0"
                        style="width: 100%">
                        <caption>
                            Listado de Age Range
                        </caption>
                        <thead class="">
                            <tr class="align-center">
                                <th>CCN</th>
                                <th>Rango de Edad</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for age_range in query_list_age_range %}
                            <tr>
                                <td>{{ age_range.ccn_age_range }}</td>
                                <td>{{ age_range.age_range }}</td>
                                <td>
                                    <a class="btn btn-secondary btn-sm"
                                        href="/update_age_range/{{ age_range.ccn_age_range }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path
                                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                            <path fill-rule="evenodd"
                                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                        </svg>
                                    </a>
                                    <a class="btn btn-danger btn-sm" id="#Eliminacion"
                                        href="/delete_age_range/{{ age_range.ccn_age_range }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path
                                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                            <path fill-rule="evenodd"
                                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="align-content-center col-md-0 col-lg-2">
            <img class="img-fluid d-block mx-auto my-auto" src="../../static/images/Econnabis_logo_green_cmyk.jpg"
                alt="" width="300" height="200" />
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">NUEVO RH</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <form class="row" action="/create_age_range" method="POST" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}

                            <div class="col-md-6">
                                {{ form.age_range.label(class="text-dark") }} {{
                                form.age_range(class="form-control") }} {% for error in
                                form.age_range.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                            <div class="mt-3 col-md-12">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                    CANCELAR
                                </button>
                                {{ form.submit(class="btn btn-success") }} {% for error in
                                form.submit.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/responsive.bootstrap5.min.js"></script>

<script>
    $(document).ready(function () {
        var table = $("#table_race").DataTable({
            language: {
                lengthMenu: "Mostrar _MENU_ registros",
                zeroRecords: "No se encontraron resultados",
                info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                infoFiltered: "(filtrado de un total de _MAX_ registros)",
                sSearch: "Buscar:",
                oPaginate: {
                    sFirst: "Primero",
                    sLast: "Último",
                    sNext: "Siguiente",
                    sPrevious: "Anterior",
                },
                sProcessing: "Procesando...",
            },
            order: [[0, "dsc"]],
            searchable: true,
            fixedHeight: true,

            responsive: true,
            paging: true,
            select: true,
            autoFill: true,
            dom: '<fl><"top"p>rt<"bottom"p><BRSPQ><"clear">',
            buttons: [
                {
                    extend: "excel",
                    title: "Archivo",
                    filename: "Export_File_xlxs",
                    text: '<img src="../../static/images/excel.png" width="50" height="50">',
                },
            ],
        });

        new $.fn.dataTable.Responsive(table, {
            details: false,
        });

        table.buttons().container().appendTo($("", table.table().container()));
    });
</script>

{% endblock %}

backend/hhrr_app/templates/defined_codes/defined_codes_arl.html
{% extends "home/base_home.html" %} {% block title %}{{ titulo }}{% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}

<div
  class="container-fluid text-end justify-content-center align-items-lg-center"
>
  <h4><strong>{{query_logged_user.employee_personal_email}}</strong></h4>
  <h6><strong>{{query_logged_user.full_name_employee}}</strong></h6>
</div>

<div class="container-fluid py-3">
  <div class="row">
    <div class="col-lg-10">
      <!-- Button trigger modal -->
      <div>
        <button
          type="button"
          class="btn btn-success btn-sm py-2"
          data-bs-toggle="modal"
          data-bs-target="#staticBackdrop"
        >
          NEW ARL
        </button>
        <div class="table-responsive col-md-12">
          <table
            class="table table-hover table-responsive"
            id="table_arl"
            cellspacing="0"
            style="width: 100%"
          >
            <caption>
              List of ARL
            </caption>
            <thead class="">
              <tr class="align-center">
                <th>CCN</th>
                <th>ARL</th>
                <th>ARL CODE</th>
                <th>ARL NIT</th>
                <th>DV</th>
                <th>ACTIONS</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for arl in query_list_arl %}
              <tr>
                <td>{{ arl.ccn_arl }}</td>
                <td>{{ arl.description_arl }}</td>
                <td>{{ arl.code_arl }}</td>
                <td>{{ arl.nit_arl }}</td>
                <td>{{ arl.dig_ver }}</td>

                <td>
                  <a
                    class="btn btn-secondary btn-sm"
                    href="/update_arl/{{ arl.ccn_arl }}"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-pencil-square"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
                      />
                      <path
                        fill-rule="evenodd"
                        d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
                      />
                    </svg>
                  </a>
                  <a
                    class="btn btn-danger btn-sm"
                    id="#Eliminacion"
                    href="/delete_arl/{{ arl.ccn_arl }}"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-trash"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
                      />
                      <path
                        fill-rule="evenodd"
                        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                      />
                    </svg>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <img
        class="img-fluid d-block mx-auto my-auto"
        src="../../static/images/Power_BI.png"
        alt=""
        width="150"
        height="150"
      />
    </div>
  </div>
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="staticBackdrop"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="staticBackdropLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">NEW ARL</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <form
              class="row g-3"
              action="/create_arl"
              method="POST"
              enctype="multipart/form-data"
            >
              {{ form.hidden_tag() }}

              <div class="col-md-12">
                {{ form.description_arl.label(class="text-dark") }} {{
                form.description_arl(class="form-control") }} {% for error in
                form.description_arl.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-3">
                {{ form.code_arl.label(class="text-dark") }} {{
                form.code_arl(class="form-control") }} {% for error in
                form.code_arl.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-4">
                {{ form.nit_arl.label(class="text-dark") }} {{
                form.nit_arl(class="form-control") }} {% for error in
                form.nit_arl.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-2">
                {{ form.dig_ver.label(class="text-dark") }} {{
                form.dig_ver(class="form-control") }} {% for error in
                form.dig_ver.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="col-md-6">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  Close
                </button>
                {{ form.submit(class="btn btn-success") }} {% for error in
                form.submit.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>

              <div class="modal-footer"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/responsive.bootstrap5.min.js"></script>

<script>
  $(document).ready(function () {
    var table = $("#table_arl").DataTable({
      searchable: true,
      fixedHeight: true,
      responsive: true,
      paging: true,
      select: true,
      autoFill: true,
      dom: '<fl><"top"p>rt<"bottom"p><BRSPQ><"clear">',
      buttons: [
        {
          extend: "excel",
          title: "Archivo",
          filename: "Export_File_xlxs",
          text: '<img src="../../static/images/excel.png" width="50" height="50">',
        },
      ],
    });

    new $.fn.dataTable.Responsive(table, {
      details: false,
    });

    table.buttons().container().appendTo($("", table.table().container()));
  });
</script>

{% endblock %}

backend/hhrr_app/templates/defined_codes/update_department.html
{% extends "home/base_home.html" %}
{% block content %}

<div class="container">
    <div class="my-50" style="margin-top: 20px;">
        <form class="row g-3" action="{{url_for('defined_codes.update_department',id_department=id_department) }}"
            method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="col-md-6">
                {{ form.id_department.label(class="text-dark") }}
                {{ form.id_department(class="form-control",value=q.id_department) }}
                {% for error in form.id_department.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            <div class="col-md-6">
                {{ form.descripcion_department.label(class="text-dark") }}
                {{ form.descripcion_department(class="form-control",value=q.descripcion_department) }}
                {% for error in form.descripcion_department.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            <div class="col-md-6">
                {{ form.ccn_country.label(class="text-dark") }}
                {{ form.ccn_country(class="form-control",value=q.ccn_country) }}
                {% for error in form.ccn_country.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            <div class="col-md-6">
                <a class="btn btn-secondary" href="/defined_code_department">Return</a>
                {{ form.submit(class="btn btn-success",value="Update") }}
                {% for error in form.submit.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            <div class="modal-footer">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio a repellendus molestias
                    natus sapiente totam incidunt animi, nostrum enim necessitatibus alias fugit
                    mollitia libero eos obcaecati, cupiditate adipisci possimus. Libero.</p>
            </div>
        </form>
    </div>
</div>
{% endblock %}